#!/bin/bash

DOTS="$HOME/Dev/PersonalScripts/dots"

cp $HOME/.vimrc "$DOTS/.vimrc"
cp $HOME/.i3/config "$DOTS/i3-gaps"
cp $HOME/.zshrc "$DOTS/.zshrc"
cp $HOME/.Xresources "$DOTS/.Xresources"
cp $HOME/.config/qutebrowser/config.py "$DOTS/../qutebrowser/config.py"
cp $HOME/.config/compton.conf "$DOTS/../compton/compton.conf"
cp $HOME/.vim/colors/* "$DOTS/../vim/colors/"
