#!/bin/bash

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

cp "$HOME/.vimrc" "$PROJECT_ROOT/dots/.vimrc"
cp "$HOME/.zshrc" "$PROJECT_ROOT/dots/.zshrc"
cp "$HOME/.config/qutebrowser/config.py" "$PROJECT_ROOT/dots/qutebrowser/config.py"
cp "$HOME/.config/i3/config" "$PROJECT_ROOT/dots/i3/config"
