#!/bin/bash

while [[ $# -gt 0 ]]; do
key="$1"

case $key in
    -u|--up)
    DIRECTION="up"
    ;;
    -d|--down)
    DIRECTION="down"
    ;;
esac
shift
done

if [[ $DIRECTION == "up" ]]; then
    amixer sset 'Master' 10%+
    echo "Upped"
fi

if [[ $DIRECTION == "down" ]]; then
    amixer sset 'Master' 10%-
    echo "Downed"
fi
